language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish
addons:
    ssh_known_hosts: 62.210.170.125
before_deploy:
  - openssl aes-256-cbc aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/output artichaut@62.210.170.125:/home/www/www.vieuxsinge.com
  on:
    branch: master

env:
  global:
    secure: Vc2VmoFtLStn8Tv/BhA8mUdVwZAQ1yVRQADg2PIYuQoGCWpes1seME5EUtScA8LQIXfCOCLzwnysxi2anbnjDhGkCFzhw41g/Ky8BzqJcB/cg79iRKMc9Mei5v2c6E7hSRsn9quZT1Zu9TR/c3kuyUmPG5IUnztl7zJ23Cfc/B6oVzXoPryUKDJlDdWv5Gz66yAAhPiJaLj1/aVpsSJqJdl1Vhvb+gJNBjzvgZw3+AKqA4uyqG8pAlk99tmq1F+dTvfixrzcD2YA+c23AS1OFkVF+mBeiVLMBfs5HliqEdVkDTOknEnOjdL2oEW/81s1revUqYyqaQ0di0oX/Qj8XFWens/PgE12eWxJu7RG7wt0hbrT9al1mdZLbYa2iKhAo0nqmZzJWEXqlH1zL/weQs0FZTmVQm84NoM5AhkG0PsqzbnVAZKpHKeyPIif5pwjDHl38H0i30IqxV8KyJF+6EwEfMTJx3WPF0o1vFFzfKbQElhJ5HGndi0MGB095yyw1yrIgAe9NCdk1O47tJb62H/sSRnRvqbRZ2YMCJHMwK82ZLHTzWBSqry4vro19VtkoYrwX5lUWTrQRLcwWprgqMeuWPjDEuXdebx/kyPhIBwxPh97vTzZFKpw7IlVApcnYD3+W6NWOZHyb0G3oZmgaUg534n4p9p3pFzM09IY9Bw=
