language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish
deploy:
  provider: script
  skip_cleanup: true
  script: ghp-import $TRAVIS_BUILD_DIR/output && git push origin gh-pages
  on:
    branch: master
