language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish
deploy:
  provider: script
  skip_cleanup: true
  script: make github
  on:
    branch: master
secure: "QugMkoKS8/zvU3EUz8571WWFOjrKGFOnrNLhoxp8ALV0jXb2615k02iufbgF6OCghdUGzFpvEMjTXadJ1cWEdzivFUegFQMBNqevK5EFIb4nWJvI16Q/lqt4Uznc3pPUt/pXy6RcKI1kXSKJDiQXwhBMRNDpeGJpayVaALcBjTQVPp5wkIJC7b1VKeGdcbqA2npJWwBszT0FBNlOKTJgmUpciuwTTXDqPsikp0gmazCr3eM+OLUjQZjmTB/HX9p3qLAiEOzFPYVm5hOGqI2pvCimiuvIT9MreCTPTxcMVuzG5bGaxQwjpBeBcr0WxcoSa2AU6Lk9gbAi86qBAcesV3I/wvuucy25w4nU74NdNfWUpRJ6K4G2d5NYWxTaQq3eSAcne9jJLegw+X16ZEgIMQvH9T2162LYq6hzNoeh9WIPYSJcWLqu06h8KAVeYsBkNz2XL/XfOy+XR0eMTpNl7KBFZgZKMBtTaD5qfIGozHYt7FjbQYVQNjmIBjgouA5Gk90O5uYxgUjeHv3CgifXwhTicHwK1gLU99B51bzGwLFG3svELPF4bgZ1y8PtYxPxcK8YWYc6AhcYVPoGMCBcsHwITzaBBlXiUD4+vsWe5ivbc1kODfD/CV+XYyeVjuaYo3SW57KUzxCoEimCADYZVExc0EKORGI4Lg3eXLT9p0w="

