language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make github
env:
  global:
    secure: jR3S1cSjtDjypt7WTVZ+5pKkjvt0wcC2T74Zbr4a41iAd6/dvO536fgVfRUQdUCuda628UOpZxkiWOhcoQ7bHyP06iUUn/hscOZbcfbFL/4S861C1OMBxeTWICyp0uhvYbJ5CgJzmncZ8IzW9c8sjT3l+hbmjNiHf72WMDGwLB/ExWIGD4Ziw65mKXqhiy6RvNxcObn1AdmAkhsmecP6rKcbW80DZLqfMh/8LkWIRMJ9AU/XKShz0G8QwznHKhmgdJmO9zA/UZD2ja8BxhDPnYXHTdmhs7d8P/M6u+wtSOc93fLolle9oaqcjsf9UdbaejjM6fCfeaI6psmkAIvwow3QMBlLvHUcQI4SQsWuAAL2pODxx4TFQ8yrnum+7HT4YYL22Lo2dE9VY3OiDHX1J5TaRol7iDQeiWHlheH6b57lkX+RdGqZjuEVF1/lcBudz0cjBaDmjpHr02lIsDIzuEBSdn56i6gmNQtE7Ub5OZeI4PXet8rh7797O+CU01/9IZCxZBdo5yUrYS9MspmulJCIWiW3qLB/WPQdlJZorxXjXJiBgMSXYMqBH//DyvR3EihGHWWostU1KHCPnBiEAJVjFdTwcqAXhvkwuvrih1UR076zdfNq+NtxjPEduXk9t1Jr6coFRmtz2b11Zo4cqQZN6EVotu9zcrApXD+HaBc=
